Log mesajları eklendi.
esogu-ceng/internship-management-system pull request #102
Opened 2023-04-16 02:29 UTC by KubraOmar

2023-04-16 08:36 UTC, yagizharman submitted a review, later dismissed

2023-04-16 09:18 UTC, ykartal commented
conflict çözülmeli.

2023-04-16 09:53 UTC, hsglc approved these changes

2023-04-16 17:05 UTC, mukrime-s approved these changes

2023-04-17 06:38 UTC, yagizharman approved these changes

2023-04-17 07:51 UTC, mukrime-s approved these changes

2023-04-17 09:52 UTC, ykartal requested changes

2023-04-17 09:52 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/service/CompanyService.java
> +		}
gerek yok fazla detay boş liste dönelebilir. Boş liste bir hata olarak tanımlanmamalı.

2023-04-17 09:52 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/service/CompanyService.java
> +		log.info("Company is found successfully.");
daha veri dönmeden bunu nereden biliyoruz ki?

2023-04-17 09:52 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/service/RegisterAsCompanySupervisorService.java
> +		log.info("New company supervisor registered: {}", companySupervisor.getName());
save işlemi başarılı olmadan bu mesajı vermek doğru mu?

2023-04-17 09:52 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/service/RegisterAsCompanySupervisorService.java
> +		throw new RuntimeException("Şifreler uyuşmuyor!");
RuntimeException fırlatmıyoruz. exception paketi altına Runtime'dan kalıtım alan yeni bir exception oluşturup onu fırlatıyoruz.

2023-04-18 10:10 UTC, Melisaozzel commented
Conflictler çözülmeli

2023-04-18 15:11 UTC, zeyn-app approved these changes

2023-04-19 11:22 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/service/CompanyService.java
> +		log.info("Company is found successfully.");
@OzgeKubra burası hala aynı.

2023-04-19 11:22 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/service/CompanyService.java
> +		log.info("Deletion process is completed successfully");
silme işlemi başarılı olarak gerçekleşti mi gerçekten

2023-04-19 11:44 UTC, ykartal requested changes
Sadece yorum yapılan noktaları değil, benzer tüm sınıfları kontrol edip tüm düzeltmelerin yapılmasında fayda var.

2023-04-19 11:44 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/service/Exception/passwordsDontMatch.java
> +public class passwordsDontMatch extends ServiceException {
Sınıf isimleri büyük harfle başlar.

2023-04-19 11:44 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/service/FacultySupervisorService.java
> +			throw e;
Özel bir exception oluşturmuyorsak geleni fırlatıyorsak bırakalım ControllerADvice loglasın bunları

2023-05-05 17:00 UTC, ezgiozdikyar requested changes

2023-05-08 11:19 UTC, closed without merging