log messages added to Company & Internship services
esogu-ceng/internship-management-system pull request #104
Opened 2023-04-16 10:55 UTC by ayko20

2023-04-16 11:26 UTC, KubraOmar submitted a review, later dismissed

2023-04-16 16:12 UTC, ykartal requested changes

2023-04-16 16:12 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/service/CompanyService.java
> +		log.info("Company updated successfully.");
emin miyiz? save işlemi başarılı oldu mu gerçekten.

2023-04-16 16:12 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/service/InternshipService.java
> +		log.info("Internship date time updated successfully.");
gerçekten update oldu mu bu noktada?

2023-04-19 11:50 UTC, ayko20 commented
log ları fix ledim

#4 Task'ı done a çekilmiş ama yapılmamış. POST company endpoint'ini ekledim.

2023-04-19 11:57 UTC, melihbucak commented
Conflictler çözülmeli

2023-04-19 19:56 UTC, ykartal requested changes

2023-04-19 19:56 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/service/CompanyService.java
> +		}
Böyle bir durum söz konusu olmayacak.

2023-04-19 19:56 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/service/CompanyService.java
> +		var updatedCompany = companyRepository.save(company);
update işleminde updateDate alanının güncellenmesi gerekir.

2023-04-19 19:56 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/service/CompanyService.java
> +		var createdCompany = companyRepository.save(company);
add işlemlerinde createDate ve updateDate alanlarının doldurulması beklenir.

2023-05-01 08:40 UTC, ayko20 commented
Conflictler çözüldü. POST company kodlarım outdated olmuş, main'e çoktan eklenmiş. Bu PR özelinde servisler için log mesajları var.

2023-05-01 10:48 UTC, MerveSari26 approved these changes

2023-05-01 11:14 UTC, zeeynep approved these changes

2023-05-01 14:49 UTC, melihbucak approved these changes

2023-05-01 18:07 UTC, closed without merging