Setting fixed
esogu-ceng/internship-management-system pull request #112
Opened 2023-04-17 14:31 UTC by ergunaltindag

Setting fixed

2023-04-17 14:34 UTC, ykenanaksan submitted a review, later dismissed
Conflictin çözülmesi gerekiyor.

2023-04-17 14:42 UTC, Melisaozzel approved these changes

2023-04-17 14:45 UTC, OmerKurtuldu submitted a review, later dismissed

2023-04-17 14:52 UTC, ykenanaksan commented on src/main/java/tr/edu/ogu/ceng/dto/SettingDto.java
Bu dosya neden silindi Dto dosyası Service kısmında gerekmiyor muydu

2023-04-17 18:55 UTC, ergunaltindag commented on src/main/java/tr/edu/ogu/ceng/dto/SettingDto.java
Mainde var zaten sadece id kaldırmıştım ama idnin durması daha iyi diye düşündüm şuanlık

2023-04-17 20:30 UTC, ykartal requested changes

2023-04-17 20:38 UTC, ykartal requested changes

2023-04-17 20:38 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/service/SettingService.java
> +>>>>>>> Stashed changes
Bu satırlar bariz derlenme problemlerine sebep olur

2023-04-17 20:52 UTC, ergunaltindag commented on src/main/java/tr/edu/ogu/ceng/dto/SettingDto.java
tekrardan ekledim hocam tüm dosyalarla beraber

2023-04-18 07:51 UTC, ykartal approved these changes

2023-04-18 08:21 UTC, Melisaozzel commented
Conflict çözülmeli

2023-04-18 08:42 UTC, SudeAkkaya-ceng approved these changes

2023-04-18 08:42 UTC, Melisaozzel approved these changes

2023-04-18 09:14 UTC, ergunaltindag commented on src/main/java/tr/edu/ogu/ceng/dto/SettingDto.java
> SettingDto silinmemeli ve içerisinde frontend de ihtiyaç olacağı için createDate updateDate olmalı diye düşünüyorum

Setting dtoyu tekrar ekledim fakat Dto içinde createDate updateDate olmalıyım emin değilim

2023-04-18 09:16 UTC, zeyn-app approved these changes

2023-04-18 09:16 UTC, merged