Internship approve methodu enum ile çalışıyor ve log eklendi
esogu-ceng/internship-management-system pull request #114
Opened 2023-04-17 15:46 UTC by pastece

2023-04-17 15:59 UTC, mukrime-s submitted a review, later dismissed

2023-04-17 16:04 UTC, OmerKurtuldu submitted a review, later dismissed

2023-04-17 20:16 UTC, ykartal requested changes

2023-04-17 20:16 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/enums/InternshipStatus.java
> +	Pending, Approved, Rejected
Java code convention takip edildiğinde enum değerlerin hepsi büyük harfle yazılır. PENDING gibi

2023-04-27 17:54 UTC, yagizharman approved these changes

2023-04-28 07:42 UTC, OmerKurtuldu approved these changes

2023-04-28 07:59 UTC, ykartal approved these changes

2023-04-28 08:54 UTC, merged

2023-04-28 12:04 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/service/InternshipService.java
> +		internship.setStatus(InternshipStatus.Approved);
Derleme hatasına sebep olan bu satır herkesin gözünden kaçtı. 
@OmerKurtuldu @yagizharman @mukrime-s @pastece