İsimle ara, öğrenci ara (searchStudent) olarak değiştirildi.
esogu-ceng/internship-management-system pull request #119
Opened 2023-04-17 20:56 UTC by BoraSoylu

"studentName" / "studentSurname" / "studentNam&studentSurname" olarak query parametreleri ile öğrenci aranabilir. Benzer şekilde numara da eklenecektir.

2023-04-17 20:57 UTC, sonerozasik approved these changes

2023-04-17 20:59 UTC, SevvalKolaca submitted a review, later dismissed

2023-04-17 21:11 UTC, sonerozasik approved these changes

2023-04-17 21:33 UTC, mukrime-s approved these changes

2023-04-17 22:39 UTC, M-TalhaSahin approved these changes

2023-04-18 05:46 UTC, zeyn-app approved these changes

2023-04-18 07:26 UTC, ykartal requested changes

2023-04-28 12:35 UTC, BoraSoylu commented
Hocam bu pull request'teki yaklaşım tek endpoint ile ad, soyad, no özelliklerinden sadece biri, ikili kombinasyonları ya da aynı anda üçü ile eşleşen öğrencileri aramayı sağlayacak.  #27 numaralı issue'da istenen bu galiba. Ad, soyad, no için 3 farklı endpoint olarak mı yapalım? Üçünün aynı anda dinamik olarak aranabilmesini custom query yazarak sağlayabildik. Eğer bu performans için sorunsa if else kullanarak da yapabiliriz. JPA'de native olarak yapamamıştık, native olarak yapmayı da biraz daha araştırabiliriz. 

Ad, soyad, no şu anda endpoint'de zorunlu değil,hiç birinin endpointe verilmemesi durumu için yöntem kararlaştırıldıktan sonra exception da eklenecektir.
 @ykartal

2023-04-28 12:41 UTC, BoraSoylu commented on src/main/java/tr/edu/ogu/ceng/dao/StudentRepository.java
> +           nativeQuery = true)
Bu yaklaşım ile paging sistemindeki gibi istenilen özellikler(ad, soyad, numara) tek olarak, ikili kombinasyon olarak ya da aynı anda üçü aranabiliyor.  Tek value ile ad, soyad, numara özelliklerinde her eşleşeni mi döndürelim hocam?  #27

2023-04-29 12:51 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/dao/StudentRepository.java
> +           nativeQuery = true)
Veya olmalı yani kartal aratıyorsak adında kartal geçenler de soyadında kartal geçenler de listelenmeli

2023-04-30 16:12 UTC, BoraSoylu commented on src/main/java/tr/edu/ogu/ceng/dao/StudentRepository.java
> +           nativeQuery = true)
Tamamdır hocam istediğiniz şekilde yeniden yapıp yeni bir pull request oluşturalım.

2023-04-30 16:12 UTC, closed without merging

2023-04-30 20:44 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/dao/StudentRepository.java
> +           nativeQuery = true)
İstenen değişilliği bu PR içinde tamamlayıp bu şekilde merge yapmalıydınız

2023-05-01 01:26 UTC, BoraSoylu commented on src/main/java/tr/edu/ogu/ceng/dao/StudentRepository.java
> +           nativeQuery = true)
Evet hocam haklısınız bundan sonra daha fazla dikkat edeceğim. Değişiklik miktarı fazla olduğundan ayrı bir pull request açmıştım, sonradan düşününce ayni issue ile ilgili olduğundan buradan yapmak daha mantıklı olduğunu farkettim.