InternshipRegisteryService logs added.
esogu-ceng/internship-management-system pull request #122
Opened 2023-04-17 22:24 UTC by zeeynep

2023-04-18 06:35 UTC, Melisaozzel submitted a review, later dismissed

2023-04-18 07:00 UTC, mukrime-s approved these changes

2023-04-18 07:23 UTC, ahmthlmzn submitted a review, later dismissed

2023-04-18 07:28 UTC, ykartal requested changes

2023-04-29 09:52 UTC, MerveSari26 submitted a review, later dismissed

2023-04-30 10:27 UTC, KubraOmar approved these changes

2023-05-01 10:58 UTC, melihbucak commented
Conflict çözülmeli

2023-05-01 11:22 UTC, MerveSari26 approved these changes

2023-05-01 16:07 UTC, zeeynep commented on src/main/java/tr/edu/ogu/ceng/service/InternshipRegistryService.java
> +			log.warn("Internship registry with ID {} not found", internshipRegistry.getId());
if bloğunu düzelttim.

2023-05-01 21:17 UTC, ykartal approved these changes

2023-05-01 21:35 UTC, closed without merging