Grup1:StudentController sınıfındaki endpoint'ler DTO formatına dönüştürüldü ve log mesajları İngilizce'ye çevrildi.
esogu-ceng/internship-management-system pull request #126
Opened 2023-04-18 15:57 UTC by KubraOmar

2023-04-18 18:30 UTC, zeyn-app submitted a review, later dismissed

2023-04-18 19:36 UTC, Melisaozzel requested changes

2023-04-18 19:36 UTC, Melisaozzel commented on src/main/java/tr/edu/ogu/ceng/dto/FacultyDto.java
> +
Zaten mapper bu işlemi yapıyor burada tekrar bu constructorda böyle bi işlem yapılmasına gerek yok

2023-04-18 19:36 UTC, Melisaozzel commented on src/main/java/tr/edu/ogu/ceng/service/FacultyService.java
>  		faculty.setUpdateDate(localDateTime);
updatefaculty ve addfaculty de dto döndürmeli

2023-04-18 19:37 UTC, Melisaozzel commented on src/main/java/tr/edu/ogu/ceng/service/CompanyService.java
>  	public Company addCompany(Company company) {
addCompany de dto döndürmeli

2023-04-19 08:07 UTC, Melisaozzel requested changes

2023-04-19 08:07 UTC, Melisaozzel commented on src/main/java/tr/edu/ogu/ceng/service/CompanyService.java
>  		}
CreateDate ve UpdateDate manuel olarak burada set edilmeli kullanıcıdan dto ile istenmemeli

2023-04-19 16:35 UTC, zeyn-app submitted a review, later dismissed

2023-04-19 18:04 UTC, yagizharman approved these changes

2023-04-19 20:07 UTC, Melisaozzel commented
Conflict çözülmeli

2023-04-26 08:28 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/controller/StudentController.java
> +	@PostMapping("/saveStudent")
save çok ortada kalıyor gibi güncelleme vs ekleme. metot isminde olduğu gibi add kullanılsaydı.

2023-04-26 08:28 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/controller/StudentController.java
> +	@PutMapping("/{id}")
{id} gerek var mı? bir yol eklense "update" gibi yeterli olmaz mı?

2023-04-26 11:28 UTC, Melisaozzel commented
conflicler var çözülmeli

2023-04-28 07:51 UTC, ykartal commented
@esogu-ceng/esogu-ceng-23spring Grup1 bu PR'ı uygun şekilde sonlandırın artık.

2023-04-28 11:16 UTC, Melisaozzel approved these changes

2023-04-28 11:19 UTC, ergunaltindag approved these changes

2023-04-28 11:45 UTC, zeyn-app approved these changes

2023-04-28 11:53 UTC, merged