Servislerdeki silme işleminde silinecek öge bulunmadığında false dönecek şekilde ayarlandı.
esogu-ceng/internship-management-system pull request #127
Opened 2023-04-18 19:31 UTC by KubraOmar

2023-04-18 19:44 UTC, Melisaozzel requested changes

2023-04-18 19:44 UTC, Melisaozzel commented on src/main/java/tr/edu/ogu/ceng/service/UserService.java
> +			throw e;
Burada bir değişiklik yapılmamış

2023-04-18 20:17 UTC, KubraOmar commented on src/main/java/tr/edu/ogu/ceng/service/UserService.java
> +			throw e;
Silme işlemi olan metotlarda ortaklaşma yapıldı.Bu nedenle, bu yöntemde herhangi bir değişiklik yapılmamıştır

2023-04-19 11:25 UTC, Efekanw commented on src/main/java/tr/edu/ogu/ceng/service/FacultyService.java
> +			return false;
Bir throw işlemi gerek görülmediyse, try catch yapısını kaldırabiliriz diye düşünüyorum. 1 if-else yapısı ile kod istenileni yapabilir.

2023-04-19 16:34 UTC, zeyn-app approved these changes

2023-04-19 16:42 UTC, yagizharman approved these changes

2023-04-19 19:48 UTC, ykartal approved these changes
Bazı durumlarda exception fıtlarmak gerekecektir. Bu durumda silmek yerine nasıl bir işlem yapılacağı ileride ele alınabilir.

2023-04-19 19:48 UTC, merged