response-request pattern integration is done
esogu-ceng/internship-management-system pull request #133
Opened 2023-04-19 21:22 UTC by burakkayya

Requests don't have id, create time and update time. Without this, there is no changes in DTOs.

2023-04-19 22:44 UTC, Melisaozzel submitted a review, later dismissed

2023-04-20 04:34 UTC, ezgiozdikyar approved these changes

2023-04-20 07:00 UTC, ykartal requested changes
Bu sadece ekleme işlemi için doğru bir yaklaşım, güncelleme işlemlerinde request içinde hangi id'li verinin güncelleneceği bilgisi gerekli.

2023-04-20 08:48 UTC, Melisaozzel commented
dto ları add ve update olarak ayırmak mantıklı olabilir

2023-04-20 08:50 UTC, burakkayya commented
> Bu sadece ekleme işlemi için doğru bir yaklaşım, güncelleme işlemlerinde request içinde hangi id'li verinin güncelleneceği bilgisi gerekli.

Kesinlikle hocam. her fonksiyon için getAll update delete add işlemi için ayrı dto lar gerekli. Ben şuan öncü olması için base oluşturdum diyebilirim. Ayrıca update işleminde dto da değil ayrı bir parametre olarak id alınması gerektiğini düşünüyorum.

2023-04-21 22:53 UTC, ykartal commented
> > Bu sadece ekleme işlemi için doğru bir yaklaşım, güncelleme işlemlerinde request içinde hangi id'li verinin güncelleneceği bilgisi gerekli.
> 
> Kesinlikle hocam. her fonksiyon için getAll update delete add işlemi için ayrı dto lar gerekli. Ben şuan öncü olması için base oluşturdum diyebilirim. Ayrıca update işleminde dto da değil ayrı bir parametre olarak id alınması gerektiğini düşünüyorum.

Bu yaklaşım uzun vadede emek yoğun bir süreç oluşmasına sebep olabilir gibi duruyor.

2023-04-22 13:21 UTC, burakkayya commented
Gerekli değişiklikler ve eklemeler yapıldı, tekrardan onay bekliyorum.

2023-04-22 13:29 UTC, burakkayya commented
> > > Bu sadece ekleme işlemi için doğru bir yaklaşım, güncelleme işlemlerinde request içinde hangi id'li verinin güncelleneceği bilgisi gerekli.
> > 
> > 
> > Kesinlikle hocam. her fonksiyon için getAll update delete add işlemi için ayrı dto lar gerekli. Ben şuan öncü olması için base oluşturdum diyebilirim. Ayrıca update işleminde dto da değil ayrı bir parametre olarak id alınması gerektiğini düşünüyorum.
> 
> Bu yaklaşım uzun vadede emek yoğun bir süreç oluşmasına sebep olabilir gibi duruyor.

Hocam her metodun istediği parametreler ve dönüş tiplerinin içeriği değişebileceğini düşünüyorum, ayrıca bir entity için sadece bir response ve bir request dtonun olması ve ilgili her metodun bunu kullanması, bu dtoların içindeki metodla alakasız veriyi de isteyecektir veya dönecektir, veri zafiyeti oluşturabilir diye düşünüyorum.

2023-04-22 13:30 UTC, burakkayya commented
Gerekli değişiklikler yapıldı, onay bekliyorum.

2023-04-24 00:54 UTC, ykartal commented
> > > > Bu sadece ekleme işlemi için doğru bir yaklaşım, güncelleme işlemlerinde request içinde hangi id'li verinin güncelleneceği bilgisi gerekli.
> > > 
> > > 
> > > Kesinlikle hocam. her fonksiyon için getAll update delete add işlemi için ayrı dto lar gerekli. Ben şuan öncü olması için base oluşturdum diyebilirim. Ayrıca update işleminde dto da değil ayrı bir parametre olarak id alınması gerektiğini düşünüyorum.
> > 
> > 
> > Bu yaklaşım uzun vadede emek yoğun bir süreç oluşmasına sebep olabilir gibi duruyor.
> 
> Hocam her metodun istediği parametreler ve dönüş tiplerinin içeriği değişebileceğini düşünüyorum, ayrıca bir entity için sadece bir response ve bir request dtonun olması ve ilgili her metodun bunu kullanması, bu dtoların içindeki metodla alakasız veriyi de isteyecektir veya dönecektir, veri zafiyeti oluşturabilir diye düşünüyorum.


Riskler;
1. Bir tabloya yeni bir alan eklenmesi, mutlaka diğer request ve responseların ve hatta controller ve servis metotlarının da değişmesini gerektirir/gerektirebilir. Bu durum zaman içerisinde güncellemesi unutulacak sınıfların ortaya çıkmasına sebep olur.
2. DTO dönüşümleri farklı ve benzer sebeplerden dolayı ayrı bir konu olarak baş ağrısına dönebilir.
3. Frontend tarafta da ekstra JS, performans ve efor gerektirecek bir iş modeli oluşturur.

Bu yaklaşımı tercih edeceğimiz bir yapı olarak onaylayamıyorum.

2023-04-24 01:46 UTC, xaxe-sk commented
DTO kullanımı kapsamında uygulamanın isterlerini de göz önünde bulundurmak gerekiyor. Hazırlanan REST servisi kapalı, sadece kendi arayüzü ile haberleşen ve temel operasyonların yapılacağı bir yönetim sistemi olduğunu düşünürsek, senaryolar bağımsız olarak çok fazla genişlemeyecektir. Bu yüzden örnek olarak Company entity'si için;

1. ID alanı ile birlikte diğer tüm değerler eklenerek tek bir CompanyDTO objesi oluşturulur.
2. İlişkili olduğu entity'ler varsa; bu entityler için arayüzde Company varlığının kullanıldığı ekranda hangi bilgilere ihtiyaç olunduğunun tespiti yapılarak yardımcı DTO objeleri hazırlanıp kullanılır.

Yukarıda verdiğim örnekten yola çıkarsak; 1 DTO objesi ile şu an PR'da bulunan 5 objenin görevini yerine getirmiş olur. Uygulama tasarımı yapılırken, create işlemi için ID alanının nasıl ele alınacağı ile ilgili verilecek kararla da bu karmaşadan kurtulunmuş olur.

Sınıfları incelediğimiz zaman aslında; **UpdateCompanyRequestDto, CreateCompanyResponseDto, GetAllCompanyResponseDto, GetByIdCompanyResponseDto, UpdateCompanyResponseDto** sınıflarının bire bir aynı sınıflar olduğu görüyoruz. Bana göre bu yaklaşımda, aslında DTO'lar ile birlikte kazanmaya çalıştığımız response time ve data'yı kazanımlarını, uygulama yönetimi ve bakım masrafında çok daha fazlasını kaybediyoruz.

2023-04-24 01:48 UTC, xaxe-sk commented on src/main/java/tr/edu/ogu/ceng/dto/requests/create/CreateCompanyRequestDto.java
> +	private String phone_number;
Sınıfların çoğunda camel case yaklaşımı kullanılırken, bazı alanlarda snake case yaklaşımı kullanılmış. Genelde camel case tercih ediyoruz, standartlaştırmakta fayda var.

2023-04-25 08:22 UTC, ykartal requested changes
1. Request ve Response'lar birebir aynı ise ayrım yapmaya gerek yok, ileride gerek olması muhtemel bile olmayabilir. Bu sebeple tek DTO ile request ve response çözülür.
2. User gibi parola dönmemesi gereken ama kayıt sırasında parola alan ya da register ve save işlemlerinin ayrıştığı entityler için request response ayrılsa yeterli.
3. Constructor'ı yazmak yerine temiz kod için lombok kullanarak allargsconstructor kullanıyoruz.

2023-04-25 13:55 UTC, burakkayya commented
> 1. Request ve Response'lar birebir aynı ise ayrım yapmaya gerek yok, ileride gerek olması muhtemel bile olmayabilir. Bu sebeple tek DTO ile request ve response çözülür.
> 2. User gibi parola dönmemesi gereken ama kayıt sırasında parola alan ya da register ve save işlemlerinin ayrıştığı entityler için request response ayrılsa yeterli.
> 3. Constructor'ı yazmak yerine temiz kod için lombok kullanarak allargsconstructor kullanıyoruz.

Anladım hocam fakat en azından requestlerin hiç birinde createtime updatetime almamamız gerekir, en basitinden burdan ayrışıyorlar diye düşündüm ve kod okunurluğuna da katkısı olabilir response request olarak ayrılmasının. İsterseniz buna göre düzenleyebilirim. Ayrıca dtoların içine ellemememin sebebi arkadaşların yazdıklarının yapısını bozmamak ama dediğiniz değişiklikleri gerçekleştireceğim bu konuda. Geri dönüşünüzü bekliyorum kodu düzenlemek için.

2023-04-26 08:48 UTC, ezgiozdikyar approved these changes

2023-04-26 08:51 UTC, mukrime-s approved these changes

2023-04-26 11:27 UTC, Melisaozzel approved these changes

2023-04-26 11:27 UTC, merged