Compile errors fixed
esogu-ceng/internship-management-system pull request #145
Opened 2023-04-28 12:23 UTC by yagizharman

FacultySupervisorTest içerisindeki metodlar localDateTime türüne geçirilip compile hatası giderildi. Internshipservice içerisindeki compile hatası da düzeltildi. Güncel olarak uygulama compile oluyor

2023-04-28 15:27 UTC, mukrime-s approved these changes

2023-04-29 00:16 UTC, yunusakyol5 approved these changes

2023-04-29 07:38 UTC, ABDULHANNANAYUBI approved these changes

2023-04-29 07:50 UTC, ABDULHANNANAYUBI requested changes
InternshipTest dosyasında status alanını DTO da InternshipStatus olarak değiştirilip InternshipTest dosyasında da uygun hale getirmek gerekiyor. Yoksa testleri geçemiyoruz.

2023-04-29 09:54 UTC, MerveSari26 approved these changes

2023-04-29 10:43 UTC, ABDULHANNANAYUBI approved these changes

2023-04-29 11:20 UTC, yunusakyol5 approved these changes

2023-04-29 11:25 UTC, merged