Internship and InternshipRegistry Dto files fixed
esogu-ceng/internship-management-system pull request #148
Opened 2023-04-30 17:09 UTC by ykenanaksan

Fixed variables in DTO's

2023-04-30 20:35 UTC, yunusakyol5 requested changes

2023-04-30 20:35 UTC, yunusakyol5 commented on src/test/java/tr/edu/ogu/ceng/service/InternshipRegistryTest.java
> +		assertEquals(modelInternshipRegistry.getInternship(), actual.getInternship());
Buradaki kontrolün internship objelerinin ID değerleri ile yapılması gerekir, yoksa testler geçmeyecektir.

2023-04-30 20:35 UTC, yunusakyol5 commented on src/test/java/tr/edu/ogu/ceng/service/InternshipTest.java
> +		assertEquals(modelInternship.getCompany(), actual.getCompany());
Aynı şekilde buradaki kontrollerin de ID tabanlı yapılması gerekiyor.

2023-04-30 20:35 UTC, yunusakyol5 commented on src/test/java/tr/edu/ogu/ceng/service/InternshipTest.java
> +				.faculty(new Faculty())
Aşağıda oluşturulan modelFaculty objesi verilebilir, ayrıca user objesi de vermek gerekiyor.

2023-04-30 20:35 UTC, yunusakyol5 commented on src/test/java/tr/edu/ogu/ceng/service/InternshipTest.java
> +		when(facultySupervisorRepository.save(any(FacultySupervisor.class))).thenReturn(modelFacultySupervisor);
Aynı şekilde internship'in de save edilmesi gerekmez mi ?

2023-04-30 20:35 UTC, yunusakyol5 commented on src/test/java/tr/edu/ogu/ceng/service/InternshipTest.java
> +				.faculty(DtoFaculty)
UserDto objesi eklenebilir.

2023-04-30 20:35 UTC, yunusakyol5 commented on src/test/java/tr/edu/ogu/ceng/service/InternshipRegistryTest.java
> +				.faculty(new Faculty())
InternshipTest dosyası için bahsettiğim eklemeler yapılabilir.

2023-04-30 20:35 UTC, yunusakyol5 commented on src/test/java/tr/edu/ogu/ceng/service/InternshipRegistryTest.java
> +		when(facultySupervisorRepository.save(any(FacultySupervisor.class))).thenReturn(modelFacultySupervisor);
Internship ve InternShipRegistry save edilmeli.

2023-04-30 20:35 UTC, yunusakyol5 commented on src/test/java/tr/edu/ogu/ceng/service/InternshipRegistryTest.java
> +				.faculty(DtoFaculty)
UserDto eklenmeli.

2023-04-30 20:35 UTC, yunusakyol5 commented on src/test/java/tr/edu/ogu/ceng/service/InternshipRegistryTest.java
Dosyalar belirlenen formatta düzenlenebilir.

2023-04-30 20:56 UTC, yunusakyol5 requested changes

2023-04-30 20:56 UTC, yunusakyol5 commented on src/main/java/tr/edu/ogu/ceng/service/InternshipRegistryService.java
> +		internshipRegistry.setId((long) 0);
Burası kodun çalışma mantığına zarar vermez mi ?

2023-04-30 20:56 UTC, yunusakyol5 commented on src/main/java/tr/edu/ogu/ceng/service/InternshipService.java
> +		internship.setId((long) 0);
Burası kodun çalışma mantığına zarar vermez mi ?

2023-04-30 21:02 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/service/InternshipRegistryService.java
> +		internshipRegistry.setId((long) 0);
Bunu defalarca söyledim ama nafile sanırım

2023-04-30 21:09 UTC, ykenanaksan commented on src/test/java/tr/edu/ogu/ceng/service/InternshipRegistryTest.java
Spring Bootumdan kaynaklanan bir durumdan dolayı format düzenlemesi yapamıyorum. Bunu senin yapabilme şansın var mı ?

2023-04-30 21:21 UTC, yunusakyol5 approved these changes

2023-04-30 21:23 UTC, SevvalKolaca approved these changes

2023-04-30 21:46 UTC, ergunaltindag approved these changes

2023-05-01 08:56 UTC, M-TalhaSahin approved these changes

2023-05-01 08:56 UTC, merged