Updated student and faculty services
esogu-ceng/internship-management-system pull request #166
Opened 2023-05-04 14:07 UTC by Melisaozzel

FacultyRequestDto eklendi.
Student update metodu güncellendi.
Faculty update metodu güncellendi.
Student ve Faculty metotları request response pattern'e göre  güncellendi.

2023-05-05 11:06 UTC, burakkayya approved these changes

2023-05-05 11:32 UTC, sonerozasik requested changes

2023-05-05 11:32 UTC, sonerozasik commented on src/main/java/tr/edu/ogu/ceng/service/StudentService.java
> +		userTypeDto.setCreateDate(now);
UserType'ın oluşturulma tarihi her student eklendiğinde güncellenmemeli

2023-05-05 12:05 UTC, Melisaozzel commented on src/main/java/tr/edu/ogu/ceng/service/StudentService.java
> +		userTypeDto.setCreateDate(now);
yeni commit ile düzeltildi

2023-05-05 17:01 UTC, ezgiozdikyar requested changes

2023-05-05 22:58 UTC, Melisaozzel commented on src/main/java/tr/edu/ogu/ceng/controller/StudentController.java
>  	}
Zaten bu şekilde ekleme işlemi yaparken id vermesem de otomatik olarak dediğin gibi ekliyor. Postmande yaptığım request testlerinde de bodyde Id'yi sadece update için kullandım. Add işlemi için body içinde id vermiyorum.
Sadece id alanı farkından dolayı update ve add için ayrı request Dto'ları kod tekrarı olmaması için oluşturmadım.

2023-05-06 13:29 UTC, sonerozasik approved these changes

2023-05-06 13:39 UTC, ezgiozdikyar approved these changes

2023-05-06 13:50 UTC, burakkayya approved these changes

2023-05-06 13:50 UTC, merged