Getting student by Internship id endpoint has been added
esogu-ceng/internship-management-system pull request #182
Opened 2023-05-07 16:13 UTC by Sdrs81

2023-05-07 17:03 UTC, ABDULHANNANAYUBI submitted a review, later dismissed

2023-05-07 17:04 UTC, hsglc approved these changes

2023-05-07 21:10 UTC, yunusakyol5 requested changes

2023-05-07 21:10 UTC, yunusakyol5 commented on src/main/java/tr/edu/ogu/ceng/controller/InternshipController.java
> +	public Page<InternshipResponseDto> getAllInternshipRegistiries(@PathVariable(name = "id") Long studentId,
Bu methodun ismi getAllInternshipsByStudentId olarak kalmalı.

2023-05-07 22:03 UTC, Sdrs81 commented on src/main/java/tr/edu/ogu/ceng/controller/InternshipController.java
> +	public Page<InternshipResponseDto> getAllInternshipRegistiries(@PathVariable(name = "id") Long studentId,
Düzeltildi.

2023-05-07 23:26 UTC, yunusakyol5 approved these changes

2023-05-08 06:03 UTC, ABDULHANNANAYUBI approved these changes

2023-05-08 07:02 UTC, hcanergun approved these changes

2023-05-08 07:02 UTC, merged