getInternship ResponseDto kullanılarak geliştirildi
esogu-ceng/internship-management-system pull request #186
Opened 2023-05-08 19:29 UTC by sonerozasik

2023-05-12 07:11 UTC, ezgiozdikyar submitted a review, later dismissed

2023-05-12 08:20 UTC, ahmthlmzn approved these changes

2023-05-12 10:05 UTC, melihbucak submitted a review, later dismissed

2023-05-12 10:41 UTC, burakkayya requested changes
Her metodun içinde model mapper yaratılmış. Sınıfın özelliği olacak şekilde model mapper tanımlanmalı ve newlenmemeli.

2023-05-12 18:38 UTC, ezgiozdikyar approved these changes

2023-05-13 00:07 UTC, burakkayya approved these changes

2023-05-13 09:11 UTC, ahmthlmzn approved these changes

2023-05-13 11:01 UTC, merged