Srping security role based redirection added vs.
esogu-ceng/internship-management-system pull request #187
Opened 2023-05-09 13:11 UTC by ykartal

2023-05-09 13:12 UTC, ergunaltindag submitted a review, later dismissed

2023-05-09 13:15 UTC, melihbucak submitted a review, later dismissed

2023-05-10 06:54 UTC, sonerozasik requested changes

2023-05-10 06:54 UTC, sonerozasik commented on src/main/java/tr/edu/ogu/ceng/security/ImsUserDetailsService.java
> +		User user = userRepository.findByEmail(username);
Parametre olarak username alınmış ama user neden email ile set ediliyor?

2023-05-10 07:15 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/security/ImsUserDetailsService.java
> +		User user = userRepository.findByEmail(username);
Evet doğru

ardından 

E-posta ile giriş yapılsın gibi bir cümle kurmuştuk derste, kullanıcı adı unutulabiliyor vs diye.
bunu hem e-mail hem de username kabul edecek şekilde genişletebiliriz.

2023-05-10 07:31 UTC, sonerozasik approved these changes

2023-05-10 08:56 UTC, mukrime-s approved these changes

2023-05-10 08:56 UTC, mukrime-s commented on src/main/java/tr/edu/ogu/ceng/security/ImsUserDetailsService.java
> +		User user = userRepository.findByEmail(username);
Bildiğim kadarıyla kullanıcı doğrulama işlemlerinde kullanıcı adı olarak e-posta kullandık. Bu yüzden e posta, kullanıcı adı olarak kabul ediliyor diyebiliriz.

2023-05-10 08:56 UTC, mukrime-s commented on src/main/java/tr/edu/ogu/ceng/security/ImsUserDetailsService.java
> +		User user = userRepository.findByEmail(username);
Bana hocanın cevabı şimdi düştü, görmeden cevap vermiştim

2023-05-10 09:55 UTC, melihbucak approved these changes

2023-05-11 10:47 UTC, burakkayya approved these changes

2023-05-11 14:29 UTC, merged