Add update user endpoint.
esogu-ceng/internship-management-system pull request #215
Opened 2023-05-16 18:06 UTC by ABDULHANNANAYUBI

2023-05-16 18:35 UTC, yunusakyol5 requested changes

2023-05-16 18:35 UTC, yunusakyol5 commented on src/main/java/tr/edu/ogu/ceng/controller/UserController.java
> +	public ResponseEntity<UserDto> updateUser(@RequestBody User user) {
Burada parametre olarak DTO alınması daha iyi olmaz mı? Ayrıca DTO'lar da response-request olarak ayrılabilir.

2023-05-16 19:06 UTC, ABDULHANNANAYUBI commented on src/main/java/tr/edu/ogu/ceng/controller/UserController.java
> +	public ResponseEntity<UserDto> updateUser(@RequestBody User user) {
Değişikler yapılmıştır.

2023-05-20 08:52 UTC, hsglc approved these changes

2023-05-20 09:05 UTC, Sdrs81 approved these changes

2023-05-20 09:14 UTC, yunusakyol5 approved these changes

2023-05-20 09:40 UTC, merged