Şirketleri Listeleme ve onun CRUD işlemleri Frontendde gösterildi
esogu-ceng/internship-management-system pull request #227
Opened 2023-05-22 11:20 UTC by yagizharman

This commit adds the necessary components and logic to display a list of companies and perform CRUD operations (Create, Read, Update, Delete) on the companies.

2023-05-22 11:41 UTC, pastece submitted a review, later dismissed

2023-05-22 15:52 UTC, yagizharman commented
![listscreen](https://github.com/esogu-ceng/internship-management-system/assets/73850593/682234a8-7b4e-484e-a4bf-e240a3791e43)

2023-05-22 15:52 UTC, yagizharman commented
![updatescreen](https://github.com/esogu-ceng/internship-management-system/assets/73850593/24621fb0-afc3-420a-8075-e8f660a1b20a)

2023-05-23 11:17 UTC, yagizharman commented
Conflict çözüldükten sonra gelen ana ekran :

![image](https://github.com/esogu-ceng/internship-management-system/assets/73850593/5648e14e-f621-4e05-abe7-fe3596a41a92)

2023-05-24 15:45 UTC, mukrime-s submitted a review, later dismissed

2023-05-25 10:14 UTC, hsglc requested changes

2023-05-25 10:14 UTC, hsglc commented on clients/faculty-supervisor/src/components/CompanyList/CompanyList.tsx
> +          ))}
```
{companies.map(({ id, name, address, phoneNumber, faxNumber, email, scope, description, createDate, updateDate }) => (
  <tr key={id}>
    <td>{name}</td>
    <td>{address}</td>
    <td>{phoneNumber}</td>
    <td>{faxNumber}</td>
    <td>{email}</td>
    <td>{scope}</td>
    <td>{description}</td>
    <td>{createDate}</td>
    <td>{updateDate}</td>
    <td>
      <button className="btnupdel" onClick={() => onUpdate(id)}>
        <FontAwesomeIcon icon={faEdit} />
      </button>
      <button className="btnupdel" onClick={() => onDelete(id)}>
        <FontAwesomeIcon icon={faTrash} />
      </button>
    </td>
  </tr>
))}

```

object destructuring yaparsak daha okunaklı olabilir. Tekrar tekrar company.[fieldName] kullanımı yapmaya gerek kalmaz.

2023-05-25 10:14 UTC, hsglc commented on clients/faculty-supervisor/src/containers/CompanyListContainer/CompanyListContainer.tsx
> +  const [errorMessage, setErrorMessage] = useState('');
Type definitionları yapılmalıdır.

2023-05-25 10:17 UTC, hsglc requested changes

2023-05-25 10:17 UTC, hsglc commented on clients/faculty-supervisor/src/containers/CompanyListContainer/CompanyListContainer.tsx
> +      // Refresh the company list after successful deletion
delete işleminin başarılı olup olmadığı nasıl anlaşılıyor burada? servisten dönen response'a bakmak gerekmez mi?

2023-05-25 10:20 UTC, yagizharman commented on clients/faculty-supervisor/src/containers/CompanyListContainer/CompanyListContainer.tsx
> +      // Refresh the company list after successful deletion
Daha önce reactla uğraşmadım hiç yavaş yavaş öğreniyorum bunu nasıl elde edebilirim

2023-05-25 10:34 UTC, hsglc commented on clients/faculty-supervisor/src/containers/CompanyListContainer/CompanyListContainer.tsx
> +      // Refresh the company list after successful deletion
> Daha önce reactla uğraşmadım hiç yavaş yavaş öğreniyorum bunu nasıl elde edebilirim

```
const response await axios.delete(`/api/company/${companyId}`, {
// check response is ok.
      });
```
delete servisi çalıştıktan sonra eğer başarılıysa response olarak ne dönüyor ona bakman lazım backendden. Eğer istenen değer dönüyorsa ona göre alttaki işlemleri yapmaya devam etmelisin.

2023-05-25 19:04 UTC, hsglc approved these changes

2023-05-26 19:13 UTC, pastece approved these changes

2023-05-26 22:22 UTC, hcanergun submitted a review, later dismissed

2023-05-27 08:58 UTC, MerveSari26 approved these changes

2023-05-27 08:59 UTC, OmerKurtuldu approved these changes

2023-05-27 09:00 UTC, mukrime-s approved these changes

2023-05-27 09:00 UTC, merged

2023-05-27 09:19 UTC, melihbucak commented
En son atılan conflicts solved isimli committe yer alan faculty supervisor içinde AllInternship.tsx isimli dosyada header içinde auth verilmiş. Bunun proje kapsamında hiçbir yerde verilmemesi gerektiğini derste konuşmuştuk. Düzenlenip tekrar commitlenmeli

2023-05-27 09:52 UTC, yagizharman commented
@melihbucak Bu auth daha önceki bir merge işleminde halledilmiş efekanın yaptığı, kontrol ederseniz görebilirsiniz. @Efekanw düzenleyebilir misin uygunsa sana da.