company görüntüleme ve düzenleme ekranı eklendi
esogu-ceng/internship-management-system pull request #238
Opened 2023-05-24 18:21 UTC by M-TalhaSahin

2023-05-24 18:28 UTC, SevvalKolaca submitted a review, later dismissed

2023-05-24 18:29 UTC, zeyn-app approved these changes

2023-05-25 09:11 UTC, hsglc commented on clients/company-supervisor/src/components/CompanyRow.tsx
> +    const [displayedValue, setDisplayedValue] = useState(value);
Type definitionları yapılabilir.

2023-05-25 09:13 UTC, hsglc commented on clients/company-supervisor/src/App.tsx
> +  const [auth, setAuth] = useState('ykartal@ogu.edu.tr:sdfasdfadfasdfasdfasdf');
Type definitionları yapılabilir.

2023-05-25 09:14 UTC, hsglc commented on clients/company-supervisor/src/components/CompanyRow.tsx
> +}) => {
Type definitionı interface olarak [componentName].d.ts gibi bir dosyada tutulup oradan import edilerek kullanılsa readability açısından daha iyi olabilir.

2023-05-25 09:22 UTC, hsglc commented on clients/company-supervisor/src/components/CompanyRow.tsx
> +}) => {
ayrıca editScope ve displayedValue statelerinin initial değeri olarak, parenttan aldığın "value" propunu vermişsin. Eğer child component unmount olmuyorsa, yani parent component içerisinde child component herhangi bir sebeple kaldırılmıyorsa, prop değeri değişse bile child componentin state'inin initial değeri değişmeyecektir. Bundan dolayı da güncel değerleri tutamayabilirsin.

2023-05-25 09:29 UTC, hsglc commented on clients/company-supervisor/src/routes/Company.tsx
> +            <CompanyRow companyId={companyInfo?.id} field='ADRES' dataField='address' value={companyInfo?.address} onEditClick={handleEditClick} onSaveClick={handleSaveClick} />
`const companyRows = [
  { field: 'İSİM', dataField: 'name' },
  { field: 'ALAN', dataField: 'scope' },
  { field: 'TELEFON NUMARASI', dataField: 'phoneNumber' },
  { field: 'FAX NUMARASI', dataField: 'faxNumber' },
  { field: 'EMAIL', dataField: 'email' },
  { field: 'AÇIKLAMA', dataField: 'description' },
  { field: 'ADRES', dataField: 'address' },
];

<tbody>
  {companyRows.map(({ field, dataField }) => (
    <CompanyRow
      key={dataField}
      companyId={companyInfo?.id}
      field={field}
      dataField={dataField}
      value={companyInfo?.[dataField]}
      onEditClick={handleEditClick}
      onSaveClick={handleSaveClick}
    />
  ))}
</tbody>`

readability ve maintainablity açısından bu kullanım daha iyi olabilir. İleride yeni field'lar eklenmek istendiğinde sadece **companyRows** array'ine yeni bir obje eklemek yeterli olacaktır.

2023-05-25 09:33 UTC, hsglc commented on clients/company-supervisor/src/routes/Company.tsx
> +            <CompanyRow companyId={companyInfo?.id} field='ADRES' dataField='address' value={companyInfo?.address} onEditClick={handleEditClick} onSaveClick={handleSaveClick} />
<tbody>
  {companyRows.map(({ field, dataField }) => (
    <CompanyRow
      key={dataField}
      companyId={companyInfo?.id}
      field={field}
      dataField={dataField}
      value={companyInfo?.[dataField]}
      onEditClick={handleEditClick}
      onSaveClick={handleSaveClick}
    />
  ))}
</tbody>


readability ve maintainablity açısından bu kullanım daha iyi olabilir. İleride yeni field'lar eklenmek istendiğinde sadece **companyRows** array'ine yeni bir obje eklemek yeterli olacaktır.

2023-05-25 09:44 UTC, hsglc commented on clients/company-supervisor/src/routes/Company.tsx
> +import React, { useEffect, useState } from 'react';
React 17 sürümünden sonra React'ı import etmeye gerek kalmadı istinasi durumlar dışında. [reference](https://www.chakshunyu.com/blog/why-did-and-dont-you-need-to-import-react/)

2023-05-25 10:18 UTC, hsglc requested changes

2023-05-26 10:16 UTC, M-TalhaSahin commented on clients/company-supervisor/src/routes/Company.tsx
> +      console.error('An error occurred while updating company', error);
evet burda kontrol etmek amaçlı loglamıştım geliştirme bittiğinde logları kaldırılıp daha sağlıklı bir identifier eklenebilir

2023-05-26 10:32 UTC, hcanergun approved these changes

2023-05-26 10:34 UTC, SevvalKolaca approved these changes

2023-05-26 13:28 UTC, SevvalKolaca approved these changes

2023-05-26 13:29 UTC, merged

2023-05-27 06:29 UTC, ykartal commented
Bir kayıda ait düzenleme ekranı gerçekten böyle mi olmalı. 
UX açısından çok zorlayıcı, bir ayarlar ekranı için olabilir ama forma ait alanların tek tek önce düzenleme sonra güncelle sonra onayla adımlarından geçmesi bana pratik gelmedi.