Grup4-ES-Şirket Bilgileri Pop up Ekranı Eklendi
esogu-ceng/internship-management-system pull request #250
Opened 2023-05-27 02:23 UTC by Efekanw

_Şirket bilgileri Pop up ekranı olarak eklendi. Indentation düzeltildi._
**Fakülte Sorumlusu Stajlar Ekranı**
![image](https://github.com/esogu-ceng/internship-management-system/assets/56073720/5c8ce704-15e2-4f8c-9599-d60540b64593)
**Şirket Bilgisi Ekranı**
![image](https://github.com/esogu-ceng/internship-management-system/assets/56073720/a9fdcba9-cff1-4626-879e-b8cef5ae8bcf)

2023-05-27 02:28 UTC, ykenanaksan approved these changes

2023-05-27 08:24 UTC, yunusakyol5 submitted a review, later dismissed

2023-05-27 12:02 UTC, MerveSari26 approved these changes

2023-05-27 12:58 UTC, ergunaltindag submitted a review, later dismissed

2023-05-27 15:58 UTC, M-TalhaSahin approved these changes

2023-05-27 19:48 UTC, MerveSari26 requested changes
Conflict düzeltilmeli

2023-05-29 14:21 UTC, M-TalhaSahin approved these changes

2023-05-29 14:22 UTC, ykenanaksan approved these changes

2023-05-29 14:23 UTC, hcanergun approved these changes

2023-05-29 14:24 UTC, yunusakyol5 approved these changes

2023-05-29 14:27 UTC, merged