Company Supervisor geliştirildi.
esogu-ceng/internship-management-system pull request #252
Opened 2023-05-27 12:30 UTC by SevvalKolaca

Student Info pop up'ına scroll bar eklendi ve düzenlendi. Stajlar sayfasındaki approved, pending, rejected durum renkleri ayarlandı.

2023-05-27 12:30 UTC, M-TalhaSahin submitted a review, later dismissed

2023-05-27 14:01 UTC, zeyn-app approved these changes

2023-05-27 16:31 UTC, hcanergun approved these changes

2023-05-28 09:41 UTC, hsglc requested changes

2023-05-28 09:41 UTC, hsglc commented on clients/company-supervisor/src/components/InternshipRow.tsx
> +  };
```
const getStatusColor = (status: string) => {
  const statusClasses = {
    APPROVED: 'bg-green-200 p-20 rounded-full',
    REJECTED: 'bg-red-200 p-20 rounded-full',
    PENDING: 'bg-yellow-200 p-20 rounded-full',
  };

  return statusClasses[status] || '';
};

```

Bu kullanım daha okunaklı olabilir.

2023-05-28 14:10 UTC, SevvalKolaca commented on clients/company-supervisor/src/components/InternshipRow.tsx
> +  };
fikir için teşekkür ederim 👍

2023-05-28 14:20 UTC, hsglc commented on clients/company-supervisor/src/components/InternshipRow.tsx
> +  };
> fikir için teşekkür ederim 👍
👍

2023-05-28 14:22 UTC, M-TalhaSahin approved these changes

2023-05-28 14:26 UTC, zeyn-app approved these changes

2023-05-28 14:35 UTC, ykenanaksan approved these changes

2023-05-29 07:00 UTC, hsglc approved these changes

2023-05-29 08:22 UTC, sonerozasik approved these changes

2023-05-29 09:02 UTC, merged