Companies panel added
esogu-ceng/internship-management-system pull request #255
Opened 2023-05-27 15:15 UTC by ayko20

- Login sayfasındaki navbar'a **Firmalar** eklendi.

![image](https://github.com/esogu-ceng/internship-management-system/assets/42973749/f7432507-642e-4d91-ac45-4447f954a135)

- Buradan Firmaların listelendiği panele yönlendirildi.

![image](https://github.com/esogu-ceng/internship-management-system/assets/42973749/88c46df9-d9ab-430d-840e-7937ea8bb4ed)

2023-05-27 19:38 UTC, melihbucak commented
Sayfa yönlendirildiğinde sadece companies şeklinde değil public/companies şeklinde olmalı. Bir de giriş sayfası bozulmuş giriş butonu yok

2023-05-27 19:41 UTC, melihbucak commented
Proje genelinde headers içinde auth vermiyoruz artık

2023-05-27 19:49 UTC, melihbucak requested changes

2023-05-27 19:49 UTC, melihbucak commented on clients/public/src/components/Companies.tsx
> +            headers: {
Proje genelinde headers içinde auth vermiyoruz artık

2023-05-27 19:49 UTC, melihbucak commented on clients/public/src/components/Header.tsx
> +          <Link to="/companies" className="header-link-company">
Firmalara tıkladığında yönlendirilen sayfada sadece companies değil public/companies şeklinde olmalı

2023-05-27 19:49 UTC, melihbucak commented on clients/public/src/App.tsx
> -            <ToastContainer/>
ToastContainer neden silindi

2023-05-29 19:20 UTC, burakkayya reviewed
link sorunu hariç yeterli gözüküyor

2023-05-29 19:41 UTC, burakkayya requested changes
link yönlendirme çözülmeli

2023-05-30 09:05 UTC, ayko20 commented
![image](https://github.com/esogu-ceng/internship-management-system/assets/42973749/46d22504-78c4-4edc-ac43-57fc4ed8d51c)
![image](https://github.com/esogu-ceng/internship-management-system/assets/42973749/5b7f7b27-11f8-410f-b11b-ff1acbf5113a)

2023-06-05 18:26 UTC, closed without merging