StudentInfo Page Added
esogu-ceng/internship-management-system pull request #256
Opened 2023-05-27 16:05 UTC by ergunaltindag

2023-05-28 09:41 UTC, hsglc requested changes

2023-05-28 09:41 UTC, hsglc commented on clients/student/src/components/StudentInfo.tsx
> +  const SGKCheck = (value: boolean | undefined) => {
```
const SGKCheck = (value: boolean) => {

  if (value) {
    return "Var";
  } else {
    return "Yok";
  }
};
```
Bu kullanım daha doğru olur gibi.

2023-05-28 10:08 UTC, ergunaltindag commented on clients/student/src/components/StudentInfo.tsx
> +  const SGKCheck = (value: boolean | undefined) => {
Şimdi kontrol edebilir misin ve neden kullanım daha doğru sence

2023-05-29 08:50 UTC, Melisaozzel requested changes

2023-05-29 08:50 UTC, Melisaozzel commented on clients/student/src/components/StudentInfo.tsx
> +      },
headers içinde artık auth vermiyoruz

2023-05-29 08:52 UTC, ergunaltindag commented on clients/student/src/components/StudentInfo.tsx
> +      },
onu diğer değişiklik ile düzelteceğimi yanına eklemiştim ama

2023-05-29 09:13 UTC, hsglc approved these changes

2023-05-29 11:19 UTC, ykenanaksan submitted a review, later dismissed

2023-05-29 16:33 UTC, sonerozasik requested changes

2023-05-29 16:33 UTC, sonerozasik commented on clients/student/src/App.tsx
>  import InternshipDashboard from "./components/InternshipDashboard";
conflict çözülmeli

2023-05-29 16:42 UTC, hsglc submitted a review, later dismissed

2024-02-27 20:12 UTC, closed without merging