Feature/admin company supervisor
esogu-ceng/internship-management-system pull request #267
Opened 2023-05-29 15:42 UTC by hsglc

2023-05-29 17:09 UTC, hcanergun submitted a review, later dismissed

2023-05-29 17:23 UTC, ABDULHANNANAYUBI submitted a review, later dismissed

2023-05-29 18:33 UTC, mukrime-s approved these changes

2023-05-29 19:30 UTC, pastece approved these changes

2023-05-29 19:40 UTC, OmerKurtuldu submitted a review, later dismissed

2023-05-30 07:02 UTC, yunusakyol5 requested changes

2023-05-30 07:02 UTC, yunusakyol5 commented on clients/admin/src/App.tsx
> +            <Route path={`${root_path}/setting`} element={<GetSettings />} />
Ayarlar ekranının çalışabilmesi için bu satır "<Route path={`${root_path}/settings`} element={<GetSettings />} />" olarak düzenlenmeli.

2023-05-30 07:10 UTC, yunusakyol5 submitted a review, later dismissed

2023-05-30 12:11 UTC, hcanergun approved these changes

2023-05-30 13:56 UTC, ABDULHANNANAYUBI approved these changes

2023-05-30 13:56 UTC, ABDULHANNANAYUBI submitted a review, later dismissed

2023-06-03 18:30 UTC, hcanergun submitted a review, later dismissed

2023-06-04 14:42 UTC, yunusakyol5 submitted a review, later dismissed

2023-06-05 07:32 UTC, hcanergun approved these changes

2023-06-05 09:13 UTC, yunusakyol5 approved these changes

2023-06-05 09:14 UTC, ABDULHANNANAYUBI approved these changes

2023-06-05 09:21 UTC, merged