Changing internships status feature added.(For FacultySupervisor)
esogu-ceng/internship-management-system pull request #295
Opened 2023-06-04 22:29 UTC by yagizharman

Changing internships status feature added
Routing fixed for internship cards
Pending endpoint added to backend

2023-06-04 22:32 UTC, yunusakyol5 requested changes

2023-06-04 22:32 UTC, yunusakyol5 commented on clients/admin/src/components/GetSettings.tsx
> +import { Setting } from '../Types/SettingType';
Burası types olarak kalmalı.

2023-06-05 09:03 UTC, MerveSari26 submitted a review, later dismissed

2023-06-05 09:06 UTC, mukrime-s submitted a review, later dismissed

2023-06-05 11:07 UTC, hsglc approved these changes

2023-06-05 11:17 UTC, yunusakyol5 approved these changes

2023-06-05 11:25 UTC, ABDULHANNANAYUBI approved these changes

2023-06-05 11:34 UTC, MerveSari26 approved these changes

2023-06-05 11:34 UTC, merged