Admin Screen fix&changes
esogu-ceng/internship-management-system pull request #315
Opened 2023-06-05 22:34 UTC by yunusakyol5

2023-06-05 22:47 UTC, KubraOmar approved these changes

2023-06-06 06:52 UTC, ABDULHANNANAYUBI approved these changes

2023-06-06 08:15 UTC, hcanergun approved these changes

2023-06-06 08:21 UTC, hsglc requested changes

2023-06-06 08:21 UTC, hsglc commented on clients/admin/src/components/GetSettings.tsx
> +import "react-toastify/dist/ReactToastify.css";
kaldırılmalı

2023-06-06 09:46 UTC, hcanergun approved these changes

2023-06-06 09:47 UTC, ABDULHANNANAYUBI approved these changes

2023-06-06 09:51 UTC, merged