Internship update
esogu-ceng/internship-management-system pull request #32
Opened 2023-03-28 08:57 UTC by sonerozasik

2023-03-30 15:26 UTC, M-TalhaSahin approved these changes

2023-03-31 09:22 UTC, ykartal requested changes

2023-03-31 16:03 UTC, ykartal requested changes

2023-03-31 16:03 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/service/InternshipService.java
> +		internship.setId(internship.getId());
kendi idsini kendisine neden atıyoruz?

2023-03-31 16:28 UTC, sonerozasik commented on src/main/java/tr/edu/ogu/ceng/model/FacultySupervisor.java
> +>>>>>>> 85e19e45025e3ca7acb353485cb841f26874f099
Kusura bakmayın hocam. Debug yapmadan göndermişim. Debuglayıp hataları fixledim.

2023-03-31 19:48 UTC, ykartal submitted a review, later dismissed
Nice work

2023-03-31 22:15 UTC, BoraSoylu approved these changes

2023-03-31 22:17 UTC, zeyn-app submitted a review, later dismissed

2023-03-31 22:36 UTC, OmerKurtuldu approved these changes

2023-03-31 22:57 UTC, ykartal commented
conflictin çözülmesi lazım

2023-03-31 23:09 UTC, M-TalhaSahin submitted a review, later dismissed

2023-04-01 09:04 UTC, zeyn-app approved these changes

2023-04-01 09:06 UTC, ezgiozdikyar approved these changes

2023-04-01 09:18 UTC, Melisaozzel approved these changes

2023-04-01 09:18 UTC, merged