InternshipRegistriesUpdate
esogu-ceng/internship-management-system pull request #34
Opened 2023-03-28 09:55 UTC by yunusakyol5

Update operations added for Internship Registries

2023-03-28 19:49 UTC, ykartal requested changes

2023-03-28 19:49 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/controller/InternshipRegistriesController.java
> +	public ResponseEntity<InternshipRegistries> updateInternshipRegistries(@RequestBody InternshipRegistries internshipRegistries, @PathVariable(name="id") Long id) {
neden id obje ile birlikte değil de ayrı olarak geliyor?

2023-03-28 19:49 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/model/InternshipRegistries.java
> +	private Long internship_id;
JoinColumn kullanmamız gerekmez mi? ya da uni-direction olacaksa hiç tanımlamamıza gerek olmayabilir mi?

2023-03-31 09:25 UTC, ykartal requested changes

2023-03-31 09:25 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/model/Student.java
Neden bu dosyayı silmeye karar verdin?

2023-03-31 09:34 UTC, yunusakyol5 commented on src/main/java/tr/edu/ogu/ceng/model/Student.java
Üzerinde herhangi bir geliştirme veya düzenleme yapmadığım için hocam.

2023-03-31 09:36 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/model/Student.java
geliştirme yapmadığın her dosyayı silecek misin?

2023-03-31 11:20 UTC, yunusakyol5 commented on src/main/java/tr/edu/ogu/ceng/model/Student.java
Hayır hocam, yanlışlıkla pushladığım için silmiştim bu dosyayı. Sadece geliştirme yaptığımız dosyaların pushlanması daha doğru olmaz mı?

2023-03-31 16:06 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/model/Student.java
Şöyle; sen bir dosya ekledin ve sonradan vazgeçip silmedin, böyle olsaydı biz farketmezdik. 
Sistemde başka bir geliştirici tarafından eklenmiş olan dosyada "yanlışlıkla" değişiklik yaptın ve sildin. Şimdi bu durumda ne oldu? Başka bir geiştiricinin koduna gerek yok dedin ve silmiş oldun. Bu dosyayı silmemelisin sadece değişiklik yapmadan devam etmelisin. Düşünsene proje bitmiş ve bir tek senin bu görevin kalmış olsaydı ne yapacaktın senin değiştirdiğin dosyalar dışında tüm dosyaları silecek miydin?

2023-03-31 16:42 UTC, yunusakyol5 commented on src/main/java/tr/edu/ogu/ceng/model/Student.java
Tamamdır hocam anladım, teşekkür ederim açıklamanız için.

2023-03-31 19:50 UTC, ykartal approved these changes
Nice work

2023-04-02 11:03 UTC, closed without merging

2023-04-02 11:58 UTC, ykartal commented
Bu PR neden kapatıldı @yunusakyol5

2023-04-02 12:36 UTC, yunusakyol5 commented
Dosya isimlendirmelerinde farklılık olduğu için sanki ilgili tüm dosyalar silinip tekrar eklenmiş gibi görünüyordu hocam, bu sebeple temiz görünmesi için yeni PR üzerinden yaptım. @ykartal

2023-04-02 12:52 UTC, ykartal commented
Yine de aynı branch üzerinden çalışmaya devam edebilrdin. Main branchindeki değişiklikleri kendi çalıştığınız branch içine çekmeye alışmalıısnız.