Servicelere eksik olan loglar eklendi.
esogu-ceng/internship-management-system pull request #374
Opened 2024-03-21 14:12 UTC by yunsturann

2024-03-22 10:39 UTC, hakanyavaseng submitted a review, later dismissed

2024-03-22 13:31 UTC, zeynepdanis approved these changes

2024-03-22 20:29 UTC, Ade3b16 submitted a review, later dismissed

2024-03-22 21:41 UTC, yunsturann commented
Conflicti nasıl düzeltebilceğimi bilmiyorum yardımcı olabilecek varsa sevinirim. pr'lar mergelenince ortaya çıkmış sanırım suçum sadece log eklemekti :(

2024-03-23 22:45 UTC, ahmetoozcan commented
Merge conflict düzeltildi, main branch StudentService searchStudent commenti eksik kalmış. Tekrar review alması lazım pr'nin.

2024-03-23 22:52 UTC, bahartogaay approved these changes

2024-03-23 23:04 UTC, ykartal requested changes
Gözüme çarpan 3-4 tane log için yorum ekledim daha fazlası olabilir. 
Ancak log işlemi yaparken düşünülmesi gereken;
Akan binlerce log arasında bu log bilgisine baktığımda işime yarayan bilgiye ulaşabilecek miyim?
Mesela "user added" yeterli değil eklendi ama hangi kullanıcı. "user added: İd=16" bile yeterli değil. Genelde hangi e-post aile gelen kulanıcı eklendi acaba diye görmek isteriz.

2024-03-23 23:04 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/service/RegisterAsCompanySupervisorService.java
> +		log.info("Company Supervisor registered successfully");
hangi company supervisor, belki id ve eposta bilgisi yeterli olacaktı.

2024-03-24 09:48 UTC, yunsturann commented
Logları güncelledim fakat mainde pull yapıp branchde mergelemem gerekiyormuş sanırım. Uğraştırıcı olsa da halletmiş olmam lazım 1-2 tane gereksiz commit atmam gerekti fakat loglar güncellendi.

2024-03-24 12:57 UTC, bedevicolfaresi approved these changes

2024-03-24 13:00 UTC, Ade3b16 approved these changes

2024-03-25 07:28 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/service/CompanyService.java
> +		log.info("All companies fetched");
findall dese de sadece ilgili sayfa parametresinde istediği kadarını getiriyor aslında.

2024-03-25 07:32 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/service/InternshipEvaluateFormService.java
> +            log.info("File upload started");
loga filename de eklenebilirdi.

2024-03-25 07:32 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/service/InternshipEvaluateFormService.java
> +            log.error("File upload failed");
loga filename de eklenebilirdi.

2024-03-25 07:33 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/service/InternshipEvaluateFormService.java
> +        log.info("Getting all internship evaluate forms");
aslında pageable

2024-03-25 07:33 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/service/InternshipEvaluateFormService.java
> +            log.info("File upload completed");
filename ?

2024-03-25 07:36 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/service/StudentService.java
> +			if (students.isEmpty()){
hiç öğrenci yoksa boş liste dönülmeli null değil.

2024-03-25 20:22 UTC, kartemre approved these changes

2024-03-26 08:22 UTC, Ade3b16 approved these changes

2024-03-26 09:40 UTC, ykartal approved these changes

2024-03-26 09:40 UTC, merged