335 feature zd
esogu-ceng/internship-management-system pull request #382
Opened 2024-03-22 13:02 UTC by zeynepdanis

2024-03-22 14:42 UTC, hakanyavaseng approved these changes

2024-03-22 15:36 UTC, burakberkaydin submitted a review, later dismissed

2024-03-24 04:55 UTC, ykartal requested changes
Bu görevde sadece yeni eklenen bir öğrenci için oluşturulan bir parolanın gönderilmesi isteniyor. 
Ancak bu geliştirme parolamı unuttum işlevlerini bozmuş ve SRP'i ihlal eden bir yapı barındırıyor.

2024-03-24 04:55 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/InternshipManagementSystem.java
Bu dosyada aslında hiç bir değişikliğe ihtiyaç yoktu neden yapıldı?

2024-03-24 04:55 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/controller/FacultySupervisorController.java
> +		}
Controller katmanında bir mantık kurmayız. DTO dönüşümleri hariç tüm iş mantığı servis katmanında olmalı bu da addStudent servisinde bu işlemlerin yapılması anlamına gelir.

2024-03-24 04:55 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/controller/FacultySupervisorController.java
> + /*
Yorum bloğuna alınmış bir kod parçasını buraad istemiyoruz. İşe yaramıyorsa sileriz.

2024-03-24 04:55 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/controller/ForgotPasswordController.java
> +			 emailService.sendResetPasswordEmail(email);
emailService sadece e-posta göndermekten sorumlu olmalıdır. Password vs ile işi olmamalıdır. EmailService çağrılacaksa ForgotPasswordService tarafından çağrılmalıydı.

2024-03-24 04:55 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/service/EmailService.java
> +    private static Cache<String, String> resetRequestCache = CacheBuilder.newBuilder().maximumSize(1000)
Bu servisten basitçe sendMail(kime başlık, mesaj) gibi bir metot bekleriz. 
Single Responsibility Principle önemli.

2024-03-24 04:55 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/service/ForgotPasswordService.java
> -	public void sendResetPasswordEmail(EmailReceiverDto emailReceiver) throws Exception {
metodun kendisi değil sadece mail gönderilme kısımları buradan ayrılmalıydı.

2024-03-24 04:55 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/service/PasswordGeneratorService.java
> +@Service
Bir servis sınıfı değil de bir util sınıfı olarak tanımlanabilirdi. Zira bir transaction başlatılması ya da veritabanı erişimi ihtiyacı görünmüyor.

2024-03-26 11:26 UTC, burakberkaydin approved these changes

2024-03-26 14:32 UTC, ykartal requested changes
İhtiyaç olmayan boşluklar içeren dosyalar ile birlikte *.jspn dosyalarının geri alınması gerekli.

2024-03-26 14:32 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/controller/FacultySupervisorController.java
> +
Gereksiz bir sürü boşluk var.

2024-03-26 14:32 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/InternshipManagementSystem.java
> -}
Bu dosyada değişiklik yapmaya gerek yoktu

2024-03-26 14:32 UTC, ykartal commented on clients/student/package.json
package.json gibi json dosyalarındaki değişiklikleri geri almalısın.

2024-03-26 14:32 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/controller/StudentController.java
> +
Bu dosyada değişikliğe ihtiyacın yok gibi görünüyor sadece boşluklar eklenmiş

2024-03-26 14:32 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/controller/UserController.java
> +
Bu dosyada değişikliğe ihtiyacın yok gibi görünüyor sadece boşluklar eklenmiş

2024-03-26 14:32 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/service/FacultySupervisorService.java
Bu dosyada değişikliğe ihtiyacın yok gibi görünüyor sadece boşluklar eklenmiş ve belki de gereksiz 2 tane import eklenmiş.

2024-03-26 14:32 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/service/ForgotPasswordService.java
> +	@Autowired
Autowired yerine @AllArgsConstructor vs. kullanıyoruz.

2024-03-26 20:31 UTC, ykartal approved these changes

2024-03-26 20:31 UTC, merged