Company service için prototip mesajlar ve servis düzenlemesi
esogu-ceng/internship-management-system pull request #385
Opened 2024-03-24 07:37 UTC by hakanyavaseng

2024-03-25 07:53 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/service/CompanyService.java
> +		log.info(messageResource.getMessage("company.service.pageable.companies.fetched"));
loglar için dil değişikliği elzem bir durum değil, son kullanıcıya giden mesajların dil olarak ayrıştırılması gerekli.

2024-03-25 07:54 UTC, ykartal commented on src/main/resources/application.properties
application.properties dosyası neden silindi.

2024-03-25 07:56 UTC, ykartal requested changes
sadece kullanıcıya giden mesajları ele alalım.

2024-03-25 08:05 UTC, hakanyavaseng commented on src/main/resources/application.properties
messages_tr.properties ile aynı klasörde olarak yanlışlıkla gönderdiğim ve diğer arkadaşların properties'i ile çakışmaması için sildim hocam.

2024-03-25 09:06 UTC, ykartal commented on src/main/resources/application.properties
Bu şekilde silince artık bu dosyaya ihtiyacım kalmadı anlamına geliyor. Yani merge yaparsak bu dosya herkesten silinecek.

2024-03-26 15:37 UTC, ykartal commented
conflict giderilmeli

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/about-merge-conflicts

2024-03-28 10:06 UTC, hakanyavaseng reviewed
reviewed

2024-03-29 21:04 UTC, ykartal approved these changes

2024-03-29 21:04 UTC, merged