Endpoint test edildi ve yorum eklendi
esogu-ceng/internship-management-system pull request #388
Opened 2024-03-24 17:46 UTC by canercoskuun

2024-03-24 17:56 UTC, syrtm approved these changes

2024-03-24 18:04 UTC, ergunaltindag commented
json dosyalarını değişiklik olarak çıkman gereklimi yorum satırı eklediğin 2 dosyayı çıkman yeterli olmaz mıydı?

2024-03-25 07:45 UTC, ykartal requested changes
json dosyalarındaki değişiklikler geri alınmalı.

2024-03-25 16:10 UTC, Keremovsky requested changes
json dosyalarındaki değişiklikler geri alınmamış.

2024-03-26 10:22 UTC, HyperMachinex approved these changes

2024-03-26 11:37 UTC, Keremovsky approved these changes

2024-03-26 14:28 UTC, syrtm approved these changes

2024-03-26 14:34 UTC, ykartal approved these changes

2024-03-26 14:34 UTC, merged