Add search input
esogu-ceng/internship-management-system pull request #414
Opened 2024-03-30 08:51 UTC by JOnRMb007

Search input has been added, it works based on name number and TR ID.

2024-04-04 13:13 UTC, yunsturann requested changes
handleOnClose'u kaldırmışsınız fakat modal açılırken
document.body.style.overflow = "hidden"; eklenmişse kapanırken de
document.body.style.overflow = "auto"; yapılması gerekiyor.
Aksi taktirde arayüzde hata oluşur.

2024-04-16 10:53 UTC, JOnRMb007 commented
Tekrar kontrol edermisiniz şuanda bir sorun olmamalı sanırsam.

2024-04-16 19:50 UTC, yunsturann approved these changes

2024-04-17 06:21 UTC, yusufkepenekci approved these changes

2024-04-17 14:24 UTC, Enescsr01 approved these changes

2024-04-17 19:12 UTC, merged