66- silme- işlemlerinde -silinecek -öğe- bulunamadığında- exception -mı -olmamalı- bunun -yerine- başarılı -mesajı -dönülebilir
esogu-ceng/internship-management-system pull request #416
Opened 2024-03-31 09:22 UTC by Ismail-dry

2024-03-31 09:31 UTC, Keremovsky requested changes
React projelerindeki paketlerin versiyonları güncellenmiş, geri alınması gerek.

2024-03-31 12:26 UTC, ykartal requested changes

2024-03-31 12:26 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/service/CompanySupervisorService.java
> +        	 repository.deleteById(id);
if else gerek kalmadan deleteAllById yeterli olacaktır

2024-03-31 12:26 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/service/FacultySupervisorService.java
> +			return true;
deleteAllById bu else kısmına girmesini engelleyecektir.

2024-03-31 12:26 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/service/StudentService.java
> +			return true;
deleteAllById bu else kısmına girmesini engelleyecektir.

2024-03-31 12:27 UTC, ykartal commented
conflict giderilmeli.

2024-04-03 13:56 UTC, zephyloth approved these changes

2024-04-16 16:40 UTC, Ismail-dry commented
Hocam biz 2 kişiyiz de merge konusunda destek olabilir misiniz

2024-04-17 19:04 UTC, merged