Dbcript güncellendi ve tüm email field'ları user tablosuna taşındı. Ş…
esogu-ceng/internship-management-system pull request #46
Opened 2023-04-01 10:14 UTC by ezgiozdikyar

Şifre hatırlat endpointi

2023-04-01 11:11 UTC, sonerozasik approved these changes

2023-04-01 11:34 UTC, ykartal requested changes
tüm properties dosyaları için aynı durum gerekli

2023-04-01 11:34 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/controller/ForgotPasswordController.java
> +	            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body("Something went wrong while sending e-mail!");
Hatayı anlatan bir exception fırlatmayı tercih ediyoruz. Bu durumda try catch bloğuna gerek kalmayacaktır.

2023-04-01 11:34 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/service/ForgotPasswordService.java
> +	private String emailFrom;
Bu bilgiyi settings tablosundan alacağımızı belirttiğimi hatırlıyorum bu sebeple bu bilgi properties dosyasında yer almayacak, settings servisinden /tablosundan alınacak.

2023-04-01 11:34 UTC, ykartal commented on src/main/resources/application-dev.properties
> +spring.mail.password=crqwmmwhvkqhnifx
Değişme ihtimali olan özellikle bu 4 bilgi settings tablosunda tanımlanmalı. Settings tablosuna verileri(value) değil ama key alanları insert eden bir script eklenmesinde fayda olacaktır.

2023-04-01 13:38 UTC, ykartal requested changes

2023-04-01 13:38 UTC, ykartal commented on db-scripts/imsdb2.sql
> +ALTER TABLE ims_settings ADD COLUMN mail_password varchar NOT NULL;
Sütun olarka değil bu veriler key-value yani satır olarak tuttlacak burada alter table yerine insert komutları görmeyi bekleriz.

2023-04-01 14:10 UTC, ezgiozdikyar commented on db-scripts/imsdb2.sql
> +ALTER TABLE ims_settings ADD COLUMN mail_password varchar NOT NULL;
Düzelttim hocam.

2023-04-01 14:23 UTC, ykartal commented on db-scripts/imsdb2.sql
> +ALTER TABLE ims_settings ADD COLUMN mail_password varchar NOT NULL;
Diğerileri de düzenlenecek?

2023-04-01 21:28 UTC, sonerozasik approved these changes

2023-04-01 22:59 UTC, burakkayya approved these changes

2023-04-01 23:17 UTC, ezgiozdikyar commented on src/main/java/tr/edu/ogu/ceng/controller/ForgotPasswordController.java
> +	            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body("Something went wrong while sending e-mail!");
Try-catch bloğunu kaldırdım hocam.

2023-04-01 23:17 UTC, ezgiozdikyar commented on src/main/java/tr/edu/ogu/ceng/service/ForgotPasswordService.java
> +	private String emailFrom;
Bu kısım da settingsten gelecek şekilde düzenlendi.

2023-04-01 23:18 UTC, ezgiozdikyar commented on src/main/resources/application-dev.properties
> +spring.mail.password=crqwmmwhvkqhnifx
Kaldırdım hocam.

2023-04-02 02:30 UTC, ykartal approved these changes

2023-04-02 02:30 UTC, merged