Ergun altindag
esogu-ceng/internship-management-system pull request #47
Opened 2023-04-01 19:33 UTC by ergunaltindag

add StudentService and StudentController

2023-04-01 20:17 UTC, ykenanaksan approved these changes

2023-04-02 01:17 UTC, SudeAkkaya-ceng approved these changes

2023-04-02 02:33 UTC, ykartal requested changes
1. Diğer PR'ların incelenip benzer yaklaşımlara evrilmesinde fayda var. 
2. PR için bir değişiklik isteği varsa kapatıp yeni branch ve yeni PR üzerinden gitmiyoruz aynı Branch ve PR ile devam ediyoruz.

2023-04-02 02:33 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/service/StudentService.java
> +	public StudentService(StudentRepository studentRepository) {
Constructor ihtiyacımız varsa Lombok ile çözüyoruz. Not: AllArgsConstructor

2023-04-02 12:48 UTC, zeyn-app approved these changes

2023-04-02 12:55 UTC, ykartal approved these changes

2023-04-02 15:17 UTC, zeyn-app submitted a review, later dismissed

2023-04-02 15:20 UTC, SudeNurTokluca approved these changes

2023-04-02 15:22 UTC, ykenanaksan requested changes

2023-04-02 15:22 UTC, ykenanaksan commented on src/main/java/tr/edu/ogu/ceng/controller/StudentController.java
> +	StudentService service;
Değişken ismi değişikliği deleteStudent operasyonunu çalışmaz hale getirir.

2023-04-02 15:38 UTC, SudeNurTokluca approved these changes

2023-04-02 15:47 UTC, zeyn-app approved these changes

2023-04-02 16:58 UTC, ykenanaksan requested changes

2023-04-02 16:58 UTC, ykenanaksan commented on src/main/java/tr/edu/ogu/ceng/service/StudentService.java
> -import javax.persistence.EntityNotFoundException;
İlgili kütüphanenin silinmesi deleteStudent operasyonunda bulunan EntityNotFoundException bileşenini çalışmaz hale getirir.

2023-04-02 21:15 UTC, ergunaltindag reviewed
Services update

2023-04-03 05:56 UTC, ykartal approved these changes
Kodlarınızı commitlemeden önce derleniyor ve beklendiği gibi çalışıyor olduğundan emin olmalısınız.

2023-04-03 10:04 UTC, ykenanaksan approved these changes

2023-04-03 10:50 UTC, merged