register as company supervisor first commit
esogu-ceng/internship-management-system pull request #48
Opened 2023-04-01 22:00 UTC by burakkayya

2023-04-01 22:58 UTC, Melisaozzel approved these changes

2023-04-02 02:19 UTC, ykartal requested changes

2023-04-02 02:19 UTC, ykartal commented on pom.xml
> +		</dependency> -->
security'i neden devre dışı bıraktık?

2023-04-02 02:19 UTC, ykartal commented on pom.xml
> +		</dependency>
Bu bağımlılıklara ihtiyaç duyuldu mu gerçekten?

2023-04-02 02:19 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/controller/StudentController.java
Bu dosyayı neden sildin? Bir başkası kullanıyor olabilir mi?

2023-04-02 02:19 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/dao/CompanySupervisorDao.java
> +public interface CompanySupervisorDao extends JpaRepository<CompanySupervisor,Long>{
Aslında isimlendirme hep CompanySupervisor**Repository**  şeklinde kullanıldı.

2023-04-02 02:19 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/dao/StudentRepository.java
Bu dosyayı neden sildin? Bir başkası kullanıyor olabilir mi?

2023-04-02 02:19 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/dto/StudentDto.java
Bu dosyayı neden sildin? Bir başkası kullanıyor olabilir mi?

2023-04-02 02:19 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/model/Student.java
Bu dosyayı neden sildin? Bir başkası kullanıyor olabilir mi?

2023-04-02 02:19 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/model/User.java
> +@Setter
Data eklendiyse ayrıca Getter ve Setter'a gerek var mı?

2023-04-02 02:19 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/service/StudentService.java
Bu dosyayı neden sildin? Bir başkası kullanıyor olabilir mi?

2023-04-02 02:19 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/service/concretes/RegisterAsCompanySupervisorManager.java
> +	ModelMapper modelMapper;
model dönüşümlerini iş mantığı dışında tutmak için Controller içinde yapsaydık?

2023-04-04 07:47 UTC, closed without merging