Update student operations added
esogu-ceng/internship-management-system pull request #49
Opened 2023-04-01 22:43 UTC by Melisaozzel

2023-04-01 22:59 UTC, burakkayya approved these changes

2023-04-02 02:27 UTC, ykartal requested changes
önce conflictler çözülmeli sonra gerekli düzenlemeler yapılmalı.

Diğer yaklaşımlardan çok farklı bir şekilde eklentiler yapıyorsunuz.

2023-04-02 02:27 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/dto/StudentDto.java
Bu dosyayı neden sildin? Bir başkası kullanıyor olabilir mi?

2023-04-02 02:27 UTC, ykartal commented on pom.xml
> -		</dependency>
Böyle bir gereksinimimiz yok, security kullanılacak ve silinmemeli.

2023-04-02 02:27 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/InternshipManagementSystem.java
> +	@Bean // uygulama oluşur oluşmaz bir modelmapperManager için bir modelmapper nesnesi  oluşturulcak.
yapılacaklar için TODO ya da FIXME kullanırız ama neden şimdi oluşturulmadı da sonraya bırakıldı böyle bir sınıfın oluşturulması

2023-04-02 02:27 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/InternshipManagementSystem.java
> +	@Bean // uygulama oluşur oluşmaz bir modelmapperManager için bir modelmapper nesnesi  oluşturulcak.
Eğer burada bean oluşturmayı düşünüyorsak genel yaklaşımımız IoC olduğundan bean tanımlarını bu şekilde yapmıyoruz.

2023-04-02 02:27 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/controller/StudentController.java
> +@RequestMapping("api/students")
@RequestMapping("api/student")  şeklinde tekil kullanıldı hep

2023-04-02 02:27 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/controller/StudentController.java
> +	public UpdateStudentResponse update (long id, @RequestBody  UpdateStudentRequest updateStudentRequest)
neden id ayrı bir parametre olarak geliyor. 

+ Her request için ayrı yapı konusunu eğer net bir şekilde eminseniz sizin grubun diğer gruplarla paylaşması gerekiyor ki herkes aynı yapıyı benimsesin.

2023-04-02 02:27 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/service/StudentManager.java
> +public class StudentManager implements StudentService{
Servis yapısı için diğer PR'ları incelemeniz de fayda var, ayrı bir interface sonra da implement eden bir sınıf oluşturulmadı hiç.

2023-04-03 19:33 UTC, closed without merging