Util class created for PageRequests. Applied on searchCompanies method on CompanyController
esogu-ceng/internship-management-system pull request #78
Opened 2023-04-07 13:35 UTC by yagizharman

PageRequest oluşturma işlemleri için bir UTİL sınıfı yazıldı ve bu sınıf CompanyController içerisindeki searchCompanies metodunda kullanıldı.

2023-04-07 13:38 UTC, yagizharman commented
ayrıca hocam StudentTest classı main branchinde bulunmasına rağmen burada da değişiklik olarak gözüküyor sebebini anlamadım ama

2023-04-07 17:46 UTC, ykartal requested changes

2023-04-07 17:46 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/controller/CompanyController.java
> +		Pageable pageable = PageRequest.of(pageNo, pageSize, Sort.by(sortBy));
PageUtil sınıfını burada kullansaydık keşke.

2023-04-07 20:43 UTC, yagizharman commented on src/main/java/tr/edu/ogu/ceng/controller/CompanyController.java
> +		Pageable pageable = PageRequest.of(pageNo, pageSize, Sort.by(sortBy));
Uyguladım hocam kontrol edebilir misiniz?

2023-04-08 18:06 UTC, MerveSari26 approved these changes

2023-04-09 21:09 UTC, ykartal approved these changes

2023-04-10 13:07 UTC, Efekanw approved these changes

2023-04-10 21:27 UTC, merged