GetAllFaculties endpoint added
esogu-ceng/internship-management-system pull request #80
Opened 2023-04-08 13:00 UTC by sanemyldz

2023-04-09 21:07 UTC, ykartal requested changes

2023-04-09 21:07 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/service/FacultyService.java
> +        facultyRepository.findAll().forEach(faculty1 -> faculties.add(faculty1));
findAll ne dönüyordu da tek tek listeye eklemek zorunda kalındı?

2023-04-09 21:07 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/controller/FacultyController.java
> +     List<Faculty> faculties=facultyService.getAllFaculties();
Artık tüm listeler için Paging durumunu uygulamalıyız.

2023-04-10 11:29 UTC, sanemyldz commented on src/main/java/tr/edu/ogu/ceng/service/FacultyService.java
> +        facultyRepository.findAll().forEach(faculty1 -> faculties.add(faculty1));
List<Faculty> dönüyor aslında hocam gereksiz ise kaldırayım.

2023-04-10 13:04 UTC, closed without merging