additions to register a student
esogu-ceng/internship-management-system pull request #83
Opened 2023-04-09 14:59 UTC by OmerKurtuldu

Öğrenci olarak kaydolmak için gerekli değişiklikleri yaptım.

2023-04-09 15:01 UTC, mukrime-s submitted a review, later dismissed

2023-04-09 21:23 UTC, ykartal requested changes

2023-04-09 21:23 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/model/Student.java
> +	private long id;
neden?

2023-04-09 21:23 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/service/StudentService.java
> +		student.setId(0);
neden?

2023-04-09 21:23 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/service/StudentService.java
> +		student.setCreateDate(new Timestamp(System.currentTimeMillis()));
studentDto --> student dönüşümü burada mı yapılmalıydı?

2023-04-09 21:23 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/service/StudentService.java
> +		response.setIdRegistryReason(student.getIdRegistryReason());
ve tersi de burada mı olmalıydı?

2023-04-12 03:03 UTC, ykartal commented
conflict çözülmesi gerekli

2023-04-15 19:10 UTC, OmerKurtuldu commented on src/main/java/tr/edu/ogu/ceng/model/Student.java
> +	private long id;
Düzelttim hocam

2023-04-15 19:11 UTC, OmerKurtuldu commented on src/main/java/tr/edu/ogu/ceng/service/StudentService.java
> +		student.setId(0);
Sildim hocam gerek yokmuş

2023-04-16 08:37 UTC, ykartal requested changes
modelMapper kullanıldı ve main içinde örneği var, artık bu kullanılabilir.

2023-04-16 08:37 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/service/StudentService.java
> +		Long userTypeId = 1L;
1L nedir?

2023-04-16 08:37 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/service/StudentService.java
> +		Long userTypeId = 1L;
çok ezber bilgi. 
Enum kullanılmalı

2023-04-16 09:53 UTC, hsglc approved these changes

2023-04-17 10:04 UTC, OmerKurtuldu commented
> modelMapper kullanıldı ve main içinde örneği var, artık bu kullanılabilir.

Hocam hangi kısımda kullanıldı. Söyleyebilir misiniz?

2023-04-17 12:01 UTC, ykartal approved these changes

2023-04-17 12:02 UTC, OmerKurtuldu commented on src/main/java/tr/edu/ogu/ceng/enums/UserTypeEnum.java
> +    COMPANYSUPERVISORS(2),
Gözümden kaçmış hocam düzeltiyorum hemen

2023-04-17 12:08 UTC, pastece approved these changes

2023-04-17 12:14 UTC, ykartal approved these changes

2023-04-17 12:26 UTC, mukrime-s approved these changes

2023-04-17 12:27 UTC, merged