Modeller veri tabanına uygun biçimde düzenlendi.
esogu-ceng/internship-management-system pull request #85
Opened 2023-04-10 15:22 UTC by sonerozasik

Modeller ve ilişkileri düzenlendi.
User ve Student arasındaki OneToOne ilişkisi için düzenlemeler yapıldı. Not : Şuanki versiyonda Student silindiğinde Student'a ait User da siliniyor. User silindiğinde Student'ın kalabilmesi için veri tabanında Delete Action Set Null uygulanması gerekiyor (istenen tasarım bu ise).

2023-04-10 15:23 UTC, M-TalhaSahin approved these changes

2023-04-10 21:46 UTC, ykartal requested changes

2023-04-10 21:46 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/model/Student.java
> +	private Long Id;
java standartlarına göre hiç bir deişken büyük harf ile başlamaz.

2023-04-11 07:48 UTC, ykartal approved these changes

2023-04-11 08:10 UTC, M-TalhaSahin approved these changes

2023-04-11 08:11 UTC, ezgiozdikyar approved these changes

2023-04-11 08:11 UTC, merged