Exception class extended
esogu-ceng/internship-management-system pull request #90
Opened 2023-04-12 21:42 UTC by mukrime-s

2023-04-12 22:49 UTC, ykartal requested changes

2023-04-12 22:49 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/service/Exception/AccessDeniedException.java
> +    }
sadece superi çağıran bir constructor gerekli mi?

2023-04-13 20:53 UTC, mukrime-s commented on src/main/java/tr/edu/ogu/ceng/service/Exception/AccessDeniedException.java
> +    }
haklısınız  hocam sildim.

2023-04-14 09:24 UTC, ykartal requested changes

2023-04-14 09:24 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/service/Exception/DataProcessingException.java
> +	}
eklenen her exceptioj sınıfı için ayrı ayrı söylemeli miydim?

2023-04-15 00:48 UTC, ykartal approved these changes

2023-04-15 08:30 UTC, ezgiozdikyar approved these changes

2023-04-15 12:58 UTC, yunusakyol5 approved these changes

2023-04-15 13:00 UTC, merged