added pageable find students by name
esogu-ceng/internship-management-system pull request #97
Opened 2023-04-14 13:19 UTC by BoraSoylu

project should compile without problems. Will add other middleware later.

2023-04-14 14:56 UTC, yagizharman approved these changes

2023-04-14 16:04 UTC, zeyn-app submitted a review, later dismissed

2023-04-14 16:52 UTC, sonerozasik submitted a review, later dismissed

2023-04-14 17:50 UTC, ykenanaksan submitted a review, later dismissed

2023-04-15 00:48 UTC, ykartal requested changes

2023-04-15 00:48 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/service/StudentService.java
> +		// To-do Exception and Logging
TODO olarak yazılır.

2023-04-15 11:51 UTC, M-TalhaSahin approved these changes

2023-04-15 11:56 UTC, zeyn-app approved these changes

2023-04-15 12:01 UTC, hcanergun approved these changes

2023-04-15 12:59 UTC, ykartal approved these changes

2023-04-15 12:59 UTC, merged