Student add test
esogu-ceng/internship-management-system pull request #98
Opened 2023-04-14 17:03 UTC by hcanergun

Student classının ekleme özelliği test edildi ve testin geçtiği gözlemlendi.

2023-04-14 17:04 UTC, hcanergun commented
Hocam student ın bütün değişkenlerine atama yapılmalı mıdır, yoksa boş veya birkaç doldurma işlemi yeterli midir?

2023-04-15 00:44 UTC, ykartal requested changes

2023-04-15 00:44 UTC, ykartal commented on src/test/java/tr/edu/ogu/ceng/service/StudentTest.java
> +		final var studentToSave = Student.builder().name("Name").surname("Surname").id(6L).build();
neden final?

2023-04-15 00:44 UTC, ykartal commented on src/test/java/tr/edu/ogu/ceng/service/StudentTest.java
> +	Student student;
bu ne için var?

2023-04-15 00:44 UTC, ykartal commented on src/test/java/tr/edu/ogu/ceng/service/StudentTest.java
> +		final var actual = studentService.addStudent(new Student());
Bu testin fail olmasını bekleriz, neden? Çünkü zorunlu alanlar var ve bu notNull alanlar mutlaka parametre veriliyor olmalı. Bunlar olmadan verilen bir test fail etmeli. any(Student.class) bu kapsamda uygun görünmedi bana.

2023-04-15 00:44 UTC, ykartal commented on src/test/java/tr/edu/ogu/ceng/service/StudentTest.java
> +		final var actual = studentService.addStudent(new Student());
Bununla birlikte bu şu demek oluyor. Repository dönüyor olabilir ama servis katmanında ilgili kontrollerin yapılması bekleniyor. Ya da controllera daha gelmeden önce ilgili değerleri aldığının doğrulandığına dair testlerin eklenmesi gerekir. Sonuç olarak aslında bu test senaryosu başarılı olarak geçmek için çok uygun görünmüyor. Ne olursan ol yeşil ol denmiş gibi duruyor.

2023-04-15 13:01 UTC, hcanergun commented
Hocam burada doldurulan öğelerinde ayrı olarak orada olup olmadığının kontrolünün mü sağlanması gerekir yoksa yeterli midir?

2023-04-16 08:14 UTC, ykartal commented
> Hocam burada doldurulan öğelerinde ayrı olarak orada olup olmadığının kontrolünün mü sağlanması gerekir yoksa yeterli midir?

Aslında evet ama bu kontrolleri controller öncesinde modellerin(doğrusu dtoların) ilgili alanların üzerinde vereceğimiz notasyonlar ile kontrol edeceğiz.

2023-04-16 08:17 UTC, ykartal approved these changes

2023-04-16 08:39 UTC, yagizharman approved these changes

2023-04-16 08:53 UTC, sonerozasik approved these changes

2023-04-16 09:17 UTC, merged