Mb grup5 log
esogu-ceng/internship-management-system pull request #99
Opened 2023-04-14 23:03 UTC by melihbucak

User, faculty ve facultySupervisor servicelerine gerekli loglama işlemleri uygulandı

2023-04-15 00:55 UTC, ykartal requested changes

2023-04-15 00:55 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/model/FacultySupervisor.java
> +	private String email;
email User sınıfına/tablosuna taşınmıştı, neden tekrar ekleme gereği duyuldu.

2023-04-15 01:17 UTC, melihbucak commented on src/main/java/tr/edu/ogu/ceng/model/FacultySupervisor.java
> +	private String email;
hocam kapatmıştım aslında o pr ı

2023-04-15 01:23 UTC, melihbucak commented on src/main/java/tr/edu/ogu/ceng/model/FacultySupervisor.java
> +	private String email;
sildim

2023-04-15 06:09 UTC, ykartal requested changes

2023-04-15 06:09 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/model/FacultySupervisor.java
Bu sınıf artık olmayacak mı? Neden kaldırdık bu sınıfı?

2023-04-15 06:12 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/model/FacultySupervisor.java
> +	private String email;
şimdi; 
Soru 1: önce 3-5 satır kod simiştin, bu silinmemeli deyince dosyayı sildin ve commitledin. Sence düzelmiş olması mümkün mü? 

Soru 2: Bu haliyle bu branchte kodların derleniyor mu?

2023-04-16 08:22 UTC, ykartal approved these changes

2023-04-16 08:22 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/model/FacultySupervisor.java
> +import javax.persistence.*;
importlara müdahale etmiyoruz, IDE bizim yerimize bunu yönetiyor.

2023-04-16 08:22 UTC, ykartal commented on src/main/java/tr/edu/ogu/ceng/model/FacultySupervisor.java
> +	@OneToOne(fetch = FetchType.LAZY,cascade = CascadeType.ALL)
Bunun loglama ile ne alakası var?

2023-04-16 08:38 UTC, yagizharman approved these changes

2023-04-16 10:43 UTC, ayko20 approved these changes

2023-04-16 14:32 UTC, merged